### ISSUE TITLE
백죽은 누군가요?

### ISSUE THREAD

**Issue by GHeeJeon** [INU-Fake-Developers/potados-space#1]
<img width="313" alt="스크린샷 2021-03-11 오후 1 06 21" src="https://user-images.githubusercontent.com/47032054/110734171-969dcb80-826a-11eb-984b-f40e2eec9cdb.png">

backjook

**Comment by potados99** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ감사함다
